services:
  wp-db:
    image: mariadb:10.6
    container_name: wp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: wp8083
    volumes:
      - ./db_data:/var/lib/mysql:Z
    networks:
      - wp-network

  wp-app:
    image: wordpress:latest
    container_name: wp-app
    restart: always
    ports:
      - "8083:80"
    environment:
      WORDPRESS_DB_HOST: wp-db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root_pass
      WORDPRESS_DB_NAME: wp8083
    volumes:
      - ../wordpress:/var/www/html:Z
    networks:
      - wp-network
    depends_on:
      - wp-db

networks:
  wp-network:
    driver: bridge
